---
#docker compose file for dev env setup
version: '3'
services:
  postgresdbgo:
    container_name: postgresdbgo
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdbgo:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api-go
    environment:
      - PORT=${PORT}
      - DB_HOST=postgresdb
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - '8080:8080'
    depends_on:
      - postgresdbgo
  
volumes:
  postgresdbgo:
    external: false
